# baseurl: /cybertale.github.io
# url: https://cybertale.github.io
# url: /home/duke/cybertale.github.io/_site
url: iesfc.top
lang: zh_CN

title: 知识杂货铺
description: 不卖切糕
author: 宋强
repository: cybertale/cybertale.github.io
github.repository_url: www.github.com/cybertale

social:
  name: 宋强
  links:
    - https://github.com/cybertale

theme: jekyll-theme-hacker
paginate: 20
paginate_path: "page=:num"

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-paginator
  - jemoji